spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'postgres'
    password: 'mysecretpassword'
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
logging.level.kurylo.tech.solution: DEBUG
